### ISSUE TITLE
In-cloud buildcache error

### ISSUE THREAD

**Issue by jaybonci** [everything2/everything2#2298]
The buildcache process throws an error when it runs in the cloud pathway

**Comment by jaybonci** [comment]
```

[Container] 2022/03/21 01:33:11 Running command tools/buildcache.rb --region $AWS_REGION --bucket $BUILDCACHE_BUCKET
--
61 | tools/buildcache.rb:124:in `block (3 levels) in <main>': undefined method `has_key?' for #<String:0x0000561625251fc0> (NoMethodError)
62 | from tools/buildcache.rb:123:in `each'
63 | from tools/buildcache.rb:123:in `block (2 levels) in <main>'
64 | from tools/buildcache.rb:121:in `each'
65 | from tools/buildcache.rb:121:in `block in <main>'
66 | from tools/buildcache.rb:118:in `each'
67 | from tools/buildcache.rb:118:in `<main>'
68 | Getting buildcache from buildcache.everything2.com/last_build.json

```
